# Generated by Django 4.0.1 on 2022-01-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_a_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=30)),
                ('Date', models.CharField(max_length=30)),
                ('Time', models.CharField(max_length=30)),
                ('No_of_people', models.CharField(max_length=30)),
                ('Msg', models.CharField(max_length=30)),
            ],
        ),
    ]
