# Generated by Django 4.0.1 on 2022-01-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book_a_table',
            table='Book_a_table',
        ),
    ]
