# Generated by Django 4.0.1 on 2022-01-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_a_table_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=30, unique=True)),
                ('feedback', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
