# Generated by Django 4.0.1 on 2022-01-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Phone',
            field=models.IntegerField(max_length=30, unique=True),
        ),
    ]
