# Generated by Django 4.0.1 on 2022-01-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_feedback_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_a_table',
            name='Phone',
            field=models.IntegerField(max_length=30),
        ),
    ]
