# Generated by Django 4.0.1 on 2022-01-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_book_a_table_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_a_table',
            name='Phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Phone',
            field=models.IntegerField(unique=True),
        ),
    ]
